# The routes of the project.
#
# Each route describes how an incoming URL is goingffffddddd
# to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "app:http"
"http://{default}/":
  type: redirect
  to: "https://{default}/"
"http://{default}/ws":
  type: upstream
  upstream: "app:http"
  cache:
    enabled: false
"https://{default}/wss":
  type: upstream
  upstream: "app:http"
  cache:
    enabled: false
"https://{default}/bugfix369":
  type: redirect
  to: "https://{default}/bugfix"
